version: '3.8'
services:
  postgres:
  image: postgres:15
  environment:
    POSTGRES_DB: glitchtip
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: secret_password
  volumes:
    - pg-data:/var/lib/postgresql/data
  redis:
    image: redis:7
  web:
    image: glitchtip/glitchtip:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:secret_password@postgres:5432/glitchtip
      - SECRET_KEY=un_tres_long_secret_aleatoire_ici
      - GLITCHTIP_DOMAIN=http://localhost:8000
      - ENABLE_REGISTRATION=True # Permet de créer le premier compte
    volumes:
      - uploads:/code/uploads
volumes:
  pg-data:
  uploads: